@MAN_HostAddress = http://localhost:5133

GET {{MAN_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MAN_HostAddress}}/book/
Accept: application/json

###
POST {{MAN_HostAddress}}/book
Content-Type: application/json

{
    "isbn": 126,
    "title": "chuj",
    "author": "dupa",
    "yearPublished": 2137
}

###
PUT {{MAN_HostAddress}}/book/1
Content-Type: application/json

  {
    "id": 1,
    "isbn": 127,
    "title": "chuj1",
    "author": "dupa2",
    "yearPublished": 2137
  }

###

DELETE {{MAN_HostAddress}}/book/4

###
GET {{MAN_HostAddress}}/book/1
Accept: application/json

###
# Get all authors
GET {{MAN_HostAddress}}/author
Accept: application/json

###
# Get an author by ID
GET {{MAN_HostAddress}}/author/1
Accept: application/json

###
# Add a new author
POST {{MAN_HostAddress}}/author
Content-Type: application/json

{
  
    "firstName": "John",
    "middleName": "A.",
    "lastName": "Doe"
}

###
# Add another new author
POST {{MAN_HostAddress}}/author
Content-Type: application/json

{
    "firstName": "Jane",
    "middleName": "B.",
    "lastName": "Smith"
}

###
# Get the newly added author by ID
GET {{MAN_HostAddress}}/author/2
Accept: application/json