@MAN_HostAddress = https://localhost:7216/api

GET {{MAN_HostAddress}}/profile/6969
Accept: application/json

###
POST {{MAN_HostAddress}}/book
Content-Type: application/json

{
    "isbn": "1243242",
    "title": "Book",
    "pageCount": 120,
    "yearPublished": 1929,
    "bindingTypeId": 3,
    "publisherId": 2,
    "authorId": 3,
    "amount": 2
}
###
GET {{MAN_HostAddress}}/book
Content-Type: application/json

###
PUT {{MAN_HostAddress}}/book/
Content-Type: application/json

  {
    "id": 58419577,
    "isbn": "1243241",
    "title": "Book2",
    "pageCount": 120,
    "yearPublished": 1929,
    "bindingTypeId": 3,
    "publisherId": 2,
    "authorId": 3
  }

###

DELETE {{MAN_HostAddress}}/book/58419579

###
GET {{MAN_HostAddress}}/book/2
Accept: application/json

###
POST {{MAN_HostAddress}}/auth/login
Content-Type: application/json

{
    
    "profileName": "sweet_kristy",
    "password": "123456"
}

### Create a New Profile
POST {{MAN_HostAddress}}/api/profile
Content-Type: application/json

{
    "id": 696969,
    "firstName": "Nat",
    "lastName": "W",
    "profileName": "siematoja",
    "password": "123456",
    "role": "Admin",
    "active": true,
    "bookReads": null
}